name: Deployment
on:
  push:
    branches:
      - master
      - production
env:
  CURRENT_BRANCH: ${{ github.ref_name }}
  GCR_HOST: us.gcr.io
  GOOGLE_PROJECT_ID: p2ppsr
  GCR_IMAGE_NAME: myac-ui

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: CI=true REACT_APP_CERTIFIER_SERVER_URL=${{ env.CURRENT_BRANCH == 'production' && secrets.PROD_CERTIFIER_SERVER_URL || secrets.STAGING_CERTIFIER_SERVER_URL }} REACT_APP_CERTIFIER_PUBLIC_KEY=${{ env.CURRENT_BRANCH == 'production' && secrets.PROD_CERTIFIER_PUBLIC_KEY || secrets.STAGING_CERTIFIER_PUBLIC_KEY }} REACT_APP_IS_STAGING=${{ env.CURRENT_BRANCH == 'master' }} npm run build
      - uses: RafikFarhad/push-to-gcr-github-action@v4.1
        with:
          gcloud_service_key: ${{ secrets.DOCKER_REGISTRY_PUSH_KEY }}
          registry: ${{ env.GCR_HOST }}
          project_id: ${{ env.GOOGLE_PROJECT_ID }}
          image_name: ${{ env.GCR_IMAGE_NAME }}
          image_tag: ${{ env.CURRENT_BRANCH }}-latest
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.gcp_deploy_creds }}
      - uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ env.CURRENT_BRANCH =='production' && 'prod-myac-ui' || 'staging-myac-ui' }}
          image: "${{ env.GCR_HOST }}/${{ env.GOOGLE_PROJECT_ID }}/${{ env.GCR_IMAGE_NAME }}:${{ env.CURRENT_BRANCH }}-latest"
          timeout: 3540
          region: us-east4
